In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

In [9]:
# bảng student
cursor.execute("""
CREATE TABLE student (
    student_id INT,
    name TEXT,
    class TEXT,
    course_id INT,
    score FLOAT
)
""")

In [10]:
# Bảng course
cursor.execute("""
CREATE TABLE course (
    id INT,
    course_name TEXT
)
""")

In [33]:
# Insert dữ liệu vào bảng student
cursor.executemany("""
INSERT INTO student VALUES (?,?,?,?,?)
""", [
(1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
(2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
(3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
(4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
(5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
(6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
(7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
(8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
(9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
(10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
])

In [24]:
# insert dữ liệu vào bảng course
cursor.executemany("""
INSERT INTO course VALUES (?,?)
""", [
(12, 'Giai Tich'),
(34, 'Thong Ke'),
(26, 'Tin Hoc'),
])

In [34]:
conn.commit()

Cau 1: JOIN

In [35]:
# Tích decartes
pd.read_sql("""
SELECT * FROM student, course
""", conn)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai Tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong Ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin Hoc
3            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai Tich
4            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong Ke
5            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin Hoc
6            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai Tich
7            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong Ke
8            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin Hoc
9            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai Tich
10           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong Ke
11           2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin Hoc
12           3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai Tich
13           3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong Ke
14           3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin Hoc
15           3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai Tich
16           3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong Ke
17           3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin Hoc
18           4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai Tich
19           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong Ke
20           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin Hoc
21           4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai Tich
22           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong Ke
23           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin Hoc
24           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai Tich
25           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong Ke
26           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin Hoc
27           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai Tich
28           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong Ke
29           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin Hoc
30           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai Tich
31           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong Ke
32           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin Hoc
33           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai Tich
34           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong Ke
35           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin Hoc
36           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai Tich
37           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong Ke
38           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin Hoc
39           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai Tich
40           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong Ke
41           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin Hoc
42           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai Tich
43           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong Ke
44           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin Hoc
45           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai Tich
46           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong Ke
47           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin Hoc
48           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai Tich
49           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong Ke
50           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin Hoc
51           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai Tich
52           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong Ke
53           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin Hoc
54          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai Tich
55          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong Ke
56          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin Hoc
57          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai Tich
58          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong Ke
59          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin Hoc

In [36]:
# Inner Join
pd.read_sql("""
SELECT * 
FROM student s
INNER JOIN course c 
ON s.course_id = c.id
""", conn)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai Tich
1           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai Tich
2           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong Ke
3           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong Ke
4           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong Ke
5           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong Ke

In [37]:
# Left Join
pd.read_sql("""
SELECT * 
FROM student s
LEFT JOIN course c 
ON s.course_id = c.id
""", conn)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai Tich
1,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai Tich
2,2,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong Ke
3,2,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong Ke
4,3,Pham Van Nam,Toan Tin,NaN,7.9,NaN,NaN
5,4,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,NaN
6,5,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,NaN
7,6,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,NaN
8,7,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong Ke
9,7,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong Ke
10,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,NaN
11,9,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,NaN
12,10,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,NaN

In [38]:
# Right Join
pd.read_sql("""
SELECT * 
FROM course c
LEFT JOIN student s 
ON s.course_id = c.id
""", conn)

   id course_name  student_id               name     class  course_id  score
0  12   Giai Tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  34    Thong Ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
2  34    Thong Ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
3  26     Tin Hoc         NaN                NaN       NaN        NaN    NaN
4  12   Giai Tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
5  34    Thong Ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
6  34    Thong Ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
7  26     Tin Hoc         NaN                NaN       NaN        NaN    NaN

In [39]:
# Full Join
pd.read_sql("""
SELECT * 
FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION

SELECT * 
FROM course c
LEFT JOIN student s ON s.course_id = c.id
""", conn)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai Tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong Ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong Ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai Tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,26,Tin Hoc,None,None,None,NaN,None
12,34,Thong Ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
13,34,Thong Ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

Cau 2:

In [40]:
# Cập nhật course_id NULL
cursor.execute("""
UPDATE student
SET course_id = 20
WHERE course_id IS NULL
""")

In [41]:
# Xóa bản ghi course không tồn tại
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")
conn.commit()

In [42]:
# a. Theo lớp
pd.read_sql("""
SELECT class,
COUNT(*) AS total_student,
ROUND(AVG(score),2) AS avg_score
FROM student
GROUP BY class
""", conn)

      class  total_student  avg_score
0   Kinh Te              2        9.2
1  May Tinh              1        6.7

In [43]:
# b. Theo môn học
pd.read_sql("""
SELECT c.course_name,
COUNT(*) AS total_student,
ROUND(AVG(score),2) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)

  course_name  total_student  avg_score
0   Giai Tich              2        6.7
1    Thong Ke              4        9.2

In [44]:
# c. Phân loại thi đua
pd.read_sql("""
SELECT c.course_name,
ROUND(AVG(score),2) AS avg_score,
CASE
    WHEN AVG(score) >= 9 THEN 'Xuat sac'
    WHEN AVG(score) >= 6 THEN 'Tot'
    ELSE 'Kem'
END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)

  course_name  avg_score classification
0   Giai Tich        6.7            Tot
1    Thong Ke        9.2       Xuat sac

Cau 3:Xep Hang

In [45]:
# a. Theo điểm
pd.read_sql("""
SELECT *,
RANK() OVER (ORDER BY score DESC) AS rank
FROM student
""", conn)

   student_id               name     class  course_id  score  rank
0           2       Tran Thi Lan   Kinh Te         34    9.2     1
1           7      Bui Tien Dung   Kinh Te         34    9.2     1
2           1  Nguyen Minh Hoang  May Tinh         12    6.7     3

In [46]:
# b. Theo lớp
pd.read_sql("""
SELECT *,
RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank
FROM student
""", conn)

   student_id               name     class  course_id  score  rank
0           2       Tran Thi Lan   Kinh Te         34    9.2     1
1           7      Bui Tien Dung   Kinh Te         34    9.2     1
2           1  Nguyen Minh Hoang  May Tinh         12    6.7     1

In [47]:
# c. Theo môn học
pd.read_sql("""
SELECT *,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank
FROM student
""", conn)

   student_id               name     class  course_id  score  rank
0           1  Nguyen Minh Hoang  May Tinh         12    6.7     1
1           2       Tran Thi Lan   Kinh Te         34    9.2     1
2           7      Bui Tien Dung   Kinh Te         34    9.2     1

In [48]:
# Top 3 cao nhất
pd.read_sql("""
SELECT * FROM (
    SELECT *, RANK() OVER (ORDER BY score DESC) AS rank
    FROM student
)
WHERE rank <= 3
""", conn)

   student_id               name     class  course_id  score  rank
0           2       Tran Thi Lan   Kinh Te         34    9.2     1
1           7      Bui Tien Dung   Kinh Te         34    9.2     1
2           1  Nguyen Minh Hoang  May Tinh         12    6.7     3

In [49]:
# Top 3 thấp nhất
pd.read_sql("""
SELECT * FROM (
    SELECT *, RANK() OVER (ORDER BY score ASC) AS rank
    FROM student
)
WHERE rank <= 3
""", conn)

   student_id               name     class  course_id  score  rank
0           1  Nguyen Minh Hoang  May Tinh         12    6.7     1
1           2       Tran Thi Lan   Kinh Te         34    9.2     2
2           7      Bui Tien Dung   Kinh Te         34    9.2     2

Cau 4: graduation_date

In [50]:
cursor.execute("""
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
""")

In [51]:
cursor.execute("""
UPDATE student
SET graduation_date = datetime('now', '+' || CAST(score AS INT) || ' days')
""")
conn.commit()

In [52]:
pd.read_sql("SELECT * FROM student", conn)

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,2026-04-09 09:19:57
1,2,Tran Thi Lan,Kinh Te,34,9.2,2026-04-12 09:19:57
2,7,Bui Tien Dung,Kinh Te,34,9.2,2026-04-12 09:19:57